### ISSUE TITLE
Required Material: Testing RF Radios

### ISSUE THREAD

**Issue by csgreen3** [vkottler/senior-design#18]
- Breadboard x2
- JTAG Programmer
- 5V power supply and micro USB x2
- Jumper wire and bread board wire
- Resistors and Capacitors

**Comment by vkottler** [comment]
One consideration is that we need to power these guys off batteries so we can be mobile and test the range.

Right now I'm thinking just 1.5V AA batteries because I have the battery holders at home

* 1.5V AA battery holders (3x)
* AA batteries
* LDO 5V / 3.3V regulator to power boards in that configuration

**Comment by vkottler** [comment]
Brought quite a bit of stuff, we should have what we need
